### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by YumeMichi** [tiaguinho/gosoap#36]
```
soap, err := gosoap.SoapClient(URL)
res, err := soap.Call("__getFunctions", gosoap.Params{})
```
```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/tiaguinho/gosoap.process.MarshalXML(0xc4200a62c0, 0xc4200e2340, 0xc420168060, 0x59, 0x0, 0x0, 0x0, 0xc42015a120, 0x0, 0x0, ...)
	/xcdata/djsp/src/github.com/tiaguinho/gosoap/encode.go:27 +0x103c
github.com/tiaguinho/gosoap.(*process).MarshalXML(0xc420195c40, 0xc42015a120, 0x0, 0x0, 0x64138d, 0x7, 0x0, 0x0, 0x0, 0x0, ...)
	<autogenerated>:1 +0xaf
encoding/xml.(*printer).marshalInterface(0xc42015a120, 0x7f52ca1b8028, 0xc420195c40, 0x0, 0x0, 0x64138d, 0x7, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/encoding/xml/marshal.go:652 +0xf8
encoding/xml.(*printer).marshalValue(0xc42015a120, 0x6803a0, 0xc420195bc0, 0x16, 0x0, 0x0, 0x4af801, 0xc42015a120)
	/usr/local/go/src/encoding/xml/marshal.go:425 +0x14ae
encoding/xml.(*Encoder).Encode(0xc42015a120, 0x6803a0, 0xc420195bc0, 0xc420177000, 0x1000)
	/usr/local/go/src/encoding/xml/marshal.go:155 +0x79
encoding/xml.MarshalIndent(0x6803a0, 0xc420195bc0, 0x0, 0x0, 0x6c7461, 0x4, 0x59, 0x0, 0x0, 0x1, ...)
	/usr/local/go/src/encoding/xml/marshal.go:122 +0x1a1
github.com/tiaguinho/gosoap.(*Client).Do(0xc4200a62c0, 0xc4200e2340, 0x0, 0x0, 0x0)
	/xcdata/djsp/src/github.com/tiaguinho/gosoap/soap.go:138 +0x239
github.com/tiaguinho/gosoap.(*Client).Call(0xc4200a62c0, 0x6cdcff, 0xe, 0xc420072f90, 0xc420072f90, 0xc42006c058, 0x0)
	/xcdata/djsp/src/github.com/tiaguinho/gosoap/soap.go:61 +0x82
main.main()
	/data/test/src/main.go:22 +0x105
exit status 2
```

**Comment by tiaguinho** [comment]
Can you check if this is still having in the last release?
